services:
  - type: web
    name: nex-nodo-conferencia
    env: docker
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BQ_PROJECT_ID
        value: meli-bi-data
      - key: BQ_LOCATION
        value: US
      - key: BQ_SCAN_TABLE
        value: meli-bi-data.SBOX_MLBPLACES.nodo_package_conferences
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
